import { useContext } from 'react'
import { observer } from 'mobx-react-lite'
import Head from 'next/head.js'
import globalContext from '../context/globalContext.js'
import CardItem from './CardItem.js'
import styles from './CardList.module.css'

function CardList () {
  const { commonStore } = useContext(globalContext)
  return (
    <>
      <Head>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          ··· Annual Movies ···
        </h1>
        <div className={styles.grid}>
          {commonStore.sortedCards.map(movieCard => <CardItem key={movieCard.movieId} card={movieCard} />)}
        </div>
      </main>
    </>
  )
}

export default observer(CardList)
