import Head from 'next/head'
import Link from 'next/link'
import SyncService from '../libs/SyncService'
import styles from './index.module.css'

export default function Home ({ cards }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <nav className={styles.nav}>
        <ul>
          <li><a href='#a'>Section A</a></li>
          <li><a href='#b'>Section B</a></li>
          <li><a href='#c'>Section C</a></li>
          <li><a href='#d'>Section D</a></li>
        </ul>
      </nav>

      <main className={styles.main}>

        <h1 className={styles.title}>
          ··· Annual Movies ···
        </h1>

        <div className={styles.grid}>
          {cards.map(movieCard => <MovieCard key={movieCard.movieId} card={movieCard} />)}
        </div>
      </main>
    </>
  )
}

// Movie Card

// http://imga.am.wholegmq.beget.tech/posters/270_400/0/006afcfe6824da56fb63b3654fda0bc8523a5d0f_270_400.jpeg
// http://imga.am.wholegmq.beget.tech/270_400/0/006afcfe6824da56fb63b3654fda0bc8523a5d0f_270_400.jpeg
// process.env.MOVIE_APP_DB

const imgHosts = (process.env.NEXT_PUBLIC_MOVIE_IMG_HOST || '/').split(';')

function MovieCard ({ card }) {
  const imgHost = imgHosts[0]
  return (
    <div className={styles.card}>
      <Link href={`/${card.slug}`}>
        <div>
          <img src={`${imgHost}/270_400/${card.posterHash[0]}/${card.posterHash}_270_400.jpeg`} title={card.title} />
        </div>
        <h4 className={styles.movieTitle}>{card.title}</h4>
        <div>{card.year}</div>
      </Link>
    </div>
  )
}

export async function getServerSideProps (context) {
  const syncService = new SyncService(process.env.MOVIE_APP_DB)
  try {
    await syncService.open()

    const movies = await syncService.moviesSince(0)
    const sortedMovies = movies.sort(({ year: a, title: x }, { year: b, title: y }) => (b - a) || x.localeCompare(y))
    const images = await syncService.imagesSince(0)

    const cards = sortedMovies.map(movie => {
      const mainImage = (images.find(nextImages => nextImages.movieId === movie.movieId) || {}).images[0] ?? null
      return {
        movieId: movie.movieId,
        slug: movie.slug,
        title: movie.title,
        year: movie.year,
        posterHash: mainImage?.hash || null
      }
    })

    return {
      props: {
        cards,
        ts: new Date().toISOString()
      }
    }
  } finally {
    if (syncService.isOpen()) {
      await syncService.close()
    }
  }
}
