import Head from 'next/head'
import Link from 'next/link'
import SyncService from '../libs/SyncService'
import styles from './index.module.css'

export default function Home ({ movies }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <nav className={styles.nav}>
        <ul>
          <li><a href="#a">Section A</a></li>
          <li><a href="#b">Section B</a></li>
          <li><a href="#c">Section C</a></li>
          <li><a href="#d">Section D</a></li>
        </ul>
      </nav>

      <main className={styles.main}>

        <h1 className={styles.title}>
          ··· Annual Movies ···
        </h1>

        <div className={styles.grid}>

          {movies.map(movie => {
            return (
              <div key={movie.movieId} className={styles.card}>
                <Link href={`/${movie.slug}`}>
                  <div>IMAGE</div>
                  <h4 className={styles.movieTitle}>{movie.title}</h4>
                  <div>{movie.year}</div>
                </Link>
              </div>
            )
          })}
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps (context) {
  const syncService = new SyncService(process.env.MOVIE_APP_DB)
  try {
    await syncService.open()

    const movies = await syncService.moviesSince(0)
    const votes = await syncService.votesSince(0)
    const images = await syncService.imagesSince(0)

    return {
      props: {
        movies,
        votes,
        images,
        ts: new Date().toISOString()
      }
    }
  } finally {
    if (syncService.isOpen()) {
      await syncService.close()
    }
  }
}
